config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :cinemas do
    resources :halls do
      resources :movie_sessions do
        patch 'buy_ticket', to: 'tickets#buy_ticket'
        patch 'reserve_ticket', to: 'tickets#reserve_ticket'
      end
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update]
  
  root to: "home#index"
  
end

app/models/hall.rb
class Hall < ApplicationRecord
  belongs_to :cinema
  has_many :movie_sessions
  
  validates :name, presence: true
  validates :seats_quantity, presence: true, numericality: 
    { greater_than: 0, only_integer: true }
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  load_and_authorize_resource :cinema
  load_and_authorize_resource :hall, through: :cinema

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @hall = Hall.new(hall_params.merge(cinema: @cinema))
    if @hall.save
      redirect_to @cinema, notice: 'Hall was successfully created.'
    else
      render :new
    end
  end

  def update
    if @hall.update_attributes(hall_params)
      redirect_to @cinema, notice: 'Hall was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @hall.destroy
    redirect_to halls_url, notice: 'Hall was successfully destroyed.'
  end

  
  private

  def hall_params
    params.require(:hall).permit(:name, :seats_quantity)
  end
  
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/views/halls/_form.html.erb
<%= simple_form_for [cinema, hall] do |f| %>
  <% if hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hall.errors.count, "error") %> 
      prohibited this hall from being saved:</h2>

      <ul>
      <% hall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :seats_quantity %>

  <%= f.button :submit %>
<% end %>

app/views/halls/edit.html.erb
<h1>Editing Hall</h1>

<%= render 'form', hall: @hall, cinema: @cinema %>

<%= link_to (fa_icon "arrow-left", text: 'Back'), @cinema %>

app/views/halls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Halls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cinema</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @halls.each do |hall| %>
      <tr>
        <td><%= hall.name %></td>
        <td><%= hall.cinema %></td>
        <td><%= link_to 'Show', hall %></td>
        <td><%= link_to 'Edit', edit_hall_path(hall) %></td>
        <td><%= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hall', new_hall_path %>

app/views/halls/new.html.erb
<h1>New Hall</h1>

<%= render 'form', hall: @hall, cinema: @cinema %>

<%= link_to (fa_icon "arrow-left", text: 'Back'), @cinema %>

app/views/halls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hall.name %>
</p>

<p>
  <strong>Cinema:</strong>
  <%= @hall.cinema.name %>
</p>

<% unless @hall.movie_sessions.empty? %>
  <h3 class="text-center">This Hall's Sessions!</h3>
  <table class="table table-striped table-hover">
    <tbody>
      <% @hall.movie_sessions.each do |movie_session| %>
        <tr>
          <td>
            <%= link_to movie_session.movie.title, 
              cinema_hall_movie_session_path(@cinema, @hall, movie_session) %>
          </td>          
          <td>
            <%= movie_session.date.strftime("%A at %R %B %d, %Y") %>
          </td>
          <td>
            <%= link_to (fa_icon "pencil", text: 'Edit session'),
              edit_cinema_hall_movie_session_path(
              @cinema, @hall, movie_session) if can? :edit, movie_session %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center">No sessions!</h3>
<% end %>
<%= link_to (fa_icon "plus", text: "Add new session"), 
  new_cinema_hall_movie_session_path(@cinema, @hall) if 
  can? :new, MovieSession %>

<br><br>
<%= link_to (fa_icon "pencil-square-o", text: 'Edit'), 
  edit_cinema_hall_path(@cinema, @hall) if can? :edit, @hall %><br>
<%= link_to (fa_icon "arrow-left", text: 'Back'), @cinema %>