config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :cinemas do
    resources :halls do
      resources :movie_sessions do
        patch 'buy_ticket', to: 'tickets#buy_ticket'
        patch 'reserve_ticket', to: 'tickets#reserve_ticket'
      end
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update]
  
  root to: "home#index"
  
end

app/models/movie_session.rb
class MovieSession < ApplicationRecord
  belongs_to :movie
  belongs_to :hall
  serialize :seats, Hash
  serialize :reserved_seats, Hash
  monetize :seat_price_cents
  
  validates :date, presence: true
  validates :seat_price, presence: true
  validates :movie, presence: true
end

app/controllers/movie_sessions_controller.rb
class MovieSessionsController < ApplicationController
  load_and_authorize_resource :cinema
  load_and_authorize_resource :hall, through: :cinema
  load_and_authorize_resource :movie_session, through: :hall
  skip_before_action :authenticate_user!, only: [:show]
  
  def index
  end

  def show
    params[:seat] = params[:seat]
  end

  def new
  end

  def edit
  end

  def create
    @movie_session = MovieSession.new(movie_session_params.merge(hall: @hall))
    if @movie_session.save
      redirect_to cinema_hall_path(@cinema, @hall), 
        notice: 'Movie session was successfully created.'
    else
      render :new
    end
  end

  def update
    if @movie_session.update_attributes(movie_session_params)
      redirect_to cinema_hall_path(@cinema, @hall), 
        notice: 'Movie session was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie_session.destroy
    redirect_to movie_sessions_url, 
      notice: 'Movie session was successfully destroyed.'
  end

  
  private
  
  def movie_session_params
    params.require(:movie_session).permit(:dates, :movie_id, :seat_price, :date)
  end
  
end

app/helpers/movie_sessions_helper.rb
module MovieSessionsHelper
  
  def show_all_seats
    all_seats = ''
    (1..@movie_session.hall.seats_quantity).each do |seat_number| 
      if @movie_session.seats["#{seat_number}"] == "taken" 
        seat_status_class = 'seat-taken' 
      elsif user_signed_in? && 
        @movie_session.reserved_seats["#{seat_number}"] == current_user.id
        seat_status_class = 'seat-reserved-by-me'
      elsif @movie_session.seats["#{seat_number}"] == "reserved"
        seat_status_class = 'seat-reserved'
      else 
        seat_status_class = 'seat-available' 
      end 
      
      all_seats << link_to(
        (raw "<div class='seat #{seat_status_class}'>#{seat_number}</div>"),
        cinema_hall_movie_session_reserve_ticket_url(
        @cinema, @hall, @movie_session, :seat => seat_number),
        :method => :patch )
    end
    raw all_seats
  end
  
  def show_buy_form
    if @movie_session.seats[params[:seat]] == "taken"
      return (
        raw '<p class="seat-taken-message">This seat is already taken!</p>')
    elsif @movie_session.seats[params[:seat]] == "reserved" &&
      user_signed_in? &&
      @movie_session.reserved_seats[params[:seat]] != current_user.id
      return (
        raw '<p class="seat-reserved-message">This seat is currently reserved!
        But it might be available shortly...</p>')
    else
      return (raw "
        <p><strong>seat: </strong>#{params[:seat]}</p>
        <p><strong>price: </strong>
          #{humanized_money_with_symbol @movie_session.seat_price}
        </p>
        #{button_to 'Buy!', 
          cinema_hall_movie_session_buy_ticket_url(
          @cinema, @hall, @movie_session,:seat => params[:seat]), 
          :method => :patch, :class => 'btn btn-primary'}
      ")
    end
  end
end

app/views/movie_sessions/_form.html.erb
<%= simple_form_for [@cinema, @hall, movie_session] do |f| %>
  <%= f.error_notification %>
  <% if movie_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_session.errors.count, "error") %> prohibited this movie_session from being saved:</h2>

      <ul>
      <% movie_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.association :movie %>
    <%= f.input :seat_price, 
      label: "Seat price (#{movie_session.seat_price_currency})" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movie_sessions/edit.html.erb
<h1>Editing Movie Session</h1>

<%= render 'form', movie_session: @movie_session %>

<%= link_to (fa_icon "arrow-left", text: 'Back'), cinema_hall_path(@cinema, @hall) %>

app/views/movie_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Dates</th>
      <th>Movie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_sessions.each do |movie_session| %>
      <tr>
        <td><%= movie_session.dates %></td>
        <td><%= movie_session.movie %></td>
        <td><%= link_to 'Show', movie_session %></td>
        <td><%= link_to 'Edit', edit_movie_session_path(movie_session) %></td>
        <td><%= link_to 'Destroy', movie_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Session', new_movie_session_path %>

app/views/movie_sessions/new.html.erb
<h1>New Movie Session</h1>

<%= render 'form', movie_session: @movie_session %>

<%= link_to 'Back', cinema_hall_path(@cinema, @hall) %>

app/views/movie_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_session.movie.title %>
</p>

<div class="row">
  <div class="col-sm-3">
    <p>
      <%= image_tag @movie_session.movie.picture_url, class: 'movie-logo' %>
    </p>
  </div>
  <div class="col-sm-9">
    <p>
      <%= @movie_session.movie.description %>
    </p>
  </div>
</div>

<p>
  <strong>Date:</strong>
  <%= @movie_session.date.strftime("%A at %R %B %d, %Y") %>
</p>

<%= show_all_seats %>

<% if params[:seat] %>
  <div class="panel">
    <% if @movie_session.seats[params[:seat]] == "taken" %>
      <p class="seat-taken-message">This seat is already taken!</p>
    <% elsif @movie_session.seats[params[:seat]] == "reserved" &&
      user_signed_in? &&
      @movie_session.reserved_seats[params[:seat]] != current_user.id %>
      <p class="seat-reserved-message">This seat is currently reserved! 
      But it might be available shortly...</p>
    <% else %>
      <p><strong>seat: </strong><%= params[:seat] %></p>
      <p><strong>price: </strong>
        <%= humanized_money_with_symbol @movie_session.seat_price %>
      </p>
      <%= button_to "Buy!", 
        cinema_hall_movie_session_buy_ticket_url(@cinema, @hall, @movie_session,
        :seat => params[:seat]), :method => :patch, 
        :class => "btn btn-primary" %>      
    <% end %>
  </div>
<% end %>

<br>
<%= link_to (fa_icon "pencil-square-o", text: 'Edit'), 
  edit_cinema_hall_movie_session_path(@cinema, @hall, @movie_session) if 
  can? :edit, @movie_session %><br>
<%= link_to (fa_icon "arrow-left", text: 'Back'), root_path %>