config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :cinemas do
    resources :halls do
      resources :movie_sessions do
        patch 'buy_ticket', to: 'tickets#buy_ticket'
        patch 'reserve_ticket', to: 'tickets#reserve_ticket'
      end
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update]
  
  root to: "home#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    @movies = Movie.all
    @movie_sessions = MovieSession.includes(:movie, hall: [:cinema]).all
    if current_user
      @my_cinemas = current_user.cinemas
      @users = User.all if current_user.admin_role?
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_movie_sessions.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <% unless @movie_sessions.empty? %>
        <h3 class="text-center">Sessions!</h3>
        <table class="table table-striped table-hover">
          <tbody>
            <% @movie_sessions.each do |movie_session| %>
              <tr>
                <td>
                  <%= link_to movie_session.date.strftime("%A at %R %B %d, %Y"),
                    cinema_hall_movie_session_path(movie_session.hall.cinema,
                    movie_session.hall, movie_session) %>
                </td>
                <td>
                  <%= movie_session.hall.cinema.name %>
                </td>
                <td>
                  <%= movie_session.hall.name %>
                </td>
                <td>
                  <%= image_tag(movie_session.movie.picture_url, 
                    class: "movie-logo") %>
                </td>
                <td>
                  <%= movie_session.movie.title %>
                </td>
                <td style="max-width: 40em;">
                  <%= movie_session.movie.description %>
                </td>              
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h3 class="text-center">No sessions!</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_movies.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <% unless @movies.empty? %>
        <h3 class="text-center">Movies! Yay!</h3>
        <table class="table table-striped table-hover">
          <tbody>
            <% @movies.each do |movie| %>
              <tr>
                <td>
                  <%= image_tag(movie.picture_url, class: "movie-logo") %>
                </td>
                <td>
                  <%= movie.title %>
                </td>
                <td>
                  <%= movie.description %>
                </td>
                <% if can? :edit, Movie %>
                  <td>
                    <%= link_to 'Edit movie', edit_movie_path(movie) %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h3 class="text-center">No movies!</h3>
      <% end %>
    </div>
  </div>
  <% if can? :new, Movie %>
    <%= link_to 'Add new movie', new_movie_path %>
  <% end %>
</div>

app/views/home/_owner_cinemas.html.erb
<% if user_signed_in? && current_user.owner_role? %>
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="text-center">My Cinemas</h3>
        <% if @my_cinemas.exists? %>
          <div class="list-group cinemas-list">
            <% @my_cinemas.each do |cinema| %>
              <%= link_to(cinema.name, cinema, :class => "list-group-item") %>
            <% end %>
          </div>
        <% else %>
          <h5 class="text-center">You have no cinemas! You looser!</h5>
        <% end %>
      </div>
    </div>
    <% if can? :new, Cinema %>
      <%= link_to (fa_icon "plus-circle", text: 'Add new cinema'), 
        new_cinema_path %>
    <% elsif !current_user.approved? %>
      <p id="unapproved-user-message">Awaiting your account approval from an administrator.</p>
    <% end %>
  </div>
<% end %>

app/views/home/_unapproved_owners.html.erb
<% if can? :edit, User %>
  <h3 class="text-center">Unapproved owners' accounts</h3>
  <div class="list-group projects-list text-center" id="unapproved-owners-home">
    <% @users.where(approved: false, owner_role: true).each do |user| %>
      <%= link_to(user.name, edit_user_path(user), :class => "list-group-item") %>
    <% end %>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render "home/unapproved_owners" %>
<%= render "home/owner_cinemas" %>
<%= render "home/movie_sessions" %>