config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :cinemas do
    resources :halls do
      resources :movie_sessions do
        patch 'buy_ticket', to: 'tickets#buy_ticket'
        patch 'reserve_ticket', to: 'tickets#reserve_ticket'
      end
    end
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show, :edit, :update]
  
  root to: "home#index"
  
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  belongs_to :user
  has_many :halls
  
  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @cinema = Cinema.new(cinema_params.merge(user: current_user))
    if @cinema.save
      redirect_to @cinema, notice: 'Cinema was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cinema.update_attributes(cinema_params)
      redirect_to @cinema, notice: 'Cinema was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @cinema.destroy
    redirect_to cinemas_url, notice: 'Cinema was successfully destroyed.'
  end


  private

  def cinema_params
    params.require(:cinema).permit(:name, :address)
  end
  
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_form.html.erb
<%= simple_form_for(cinema) do |f| %>
  <% if cinema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cinema.errors.count, "error") %> prohibited this cinema from being saved:</h2>

      <ul>
      <% cinema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address %>

  <%= f.button :submit %>
    
<% end %>

app/views/cinemas/edit.html.erb
<h1>Editing Cinema</h1>

<%= render 'form', cinema: @cinema %>

<%= link_to (fa_icon "arrow-left", text: 'Back'), @cinema %>

app/views/cinemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cinemas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= cinema.name %></td>
        <td><%= cinema.address %></td>
        <td><%= cinema.user %></td>
        <td><%= link_to 'Show', cinema %></td>
        <td><%= link_to 'Edit', edit_cinema_path(cinema) %></td>
        <td><%= link_to 'Destroy', cinema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cinema', new_cinema_path %>

app/views/cinemas/new.html.erb
<h1>New Cinema</h1>

<%= render 'form', cinema: @cinema %>

<%= link_to 'Back', root_path %>

app/views/cinemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cinema.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cinema.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @cinema.user.name %>
</p>

<% unless @cinema.halls.empty? %>
  <h3 class="text-center">This Cinema's Halls!</h3>
  <table class="table table-striped table-hover">
    <tbody>
      <% @cinema.halls.each do |hall| %>
        <tr>
          <td>
            <%= link_to hall.name, cinema_hall_path(@cinema, hall) %>
          </td>
          <td>
            <%= link_to (fa_icon "pencil", text: 'Edit hall'),
              edit_cinema_hall_path(@cinema, hall) if can? :edit, Hall %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center">No halls!</h3>
<% end %>
<%= link_to (fa_icon "plus", text: "Add new hall"),
  new_cinema_hall_path(@cinema) if can? :new, Hall %>

<br><br>
<%= link_to (fa_icon "pencil-square-o", text: 'Edit cinema'),
  edit_cinema_path(@cinema) if can? :edit, @cinema %><br>
<%= link_to (fa_icon "arrow-left", text: 'Back'), root_path %>